### ISSUE TITLE
Auto-width

### ISSUE THREAD

**Issue by andli** [nirum/tableprint#13]
Love tableprint! 

Since everything is monospaced, it should be easy to set the width on each column automatically based on the longest string value of each column (and its header). Could you please implement this? It would save precious horizontal space and fit more columns.

**Comment by nirum** [comment]
This is a great suggestion! Will work on this next.

**Comment by sumanthratna** [comment]
Any update on this? I think this would be a very valuable feature to have.

**Comment by nirum** [comment]
Only two years late 😄
