### ISSUE TITLE
Drop Numpy as a hard requirement

### ISSUE THREAD

**Issue by nicktimko** [nirum/tableprint#8]
Including Numpy as a necessary requirement is extremely heavy for a terminal printer. It seems like you just use it to convert a dataframe to an array and to do a floor function on a scalar(!). The latter can be easily replicated through `math.floor` in the stdlib, and for the former, you could attempt to import Numpy if it exists inside the dataframe function (if someone's giving you a Pandas dataframe you know there'll be Numpy).

**Comment by nirum** [comment]
This is a really great suggestion! I made the fix in #9.
